In [6]:
import pandas as pd

In [7]:
pandas_ser = pd.Series([
  10,20,"Eray","Kostereli"
])

In [8]:
pandas_ser[0]

10

In [9]:
pandas_ser.values

array([10, 20, 'Eray', 'Kostereli'], dtype=object)

Indexing

In [11]:
pd_ser2 = pd.Series(["10","20","30","Eray","Rumeysa"],index=["e","r","a","y","b"])
pd_ser2

e         10
r         20
a         30
y       Eray
b    Rumeysa
dtype: str

In [12]:
pd_ser2["e"]

'10'

In [13]:
pd_ser2["a"]

'30'

In [14]:
sozluk = {
  "Eray" : 30,
  "Rumeysa" : 40,
  "Dogukam" : 50,
  "Emirhan" : 60
}

In [16]:
sozluk_pd = pd.Series(sozluk)
sozluk_pd

Eray       30
Rumeysa    40
Dogukam    50
Emirhan    60
dtype: int64

In [17]:
sozluk_pd.index

Index(['Eray', 'Rumeysa', 'Dogukam', 'Emirhan'], dtype='str')

Masking

In [19]:
mask_pd = pd.Series([1,2,3,4,5,6,7,8,9,10])

masked = mask_pd[mask_pd > 5]

In [20]:
masked

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [28]:
import os
print(os.getcwd())

/Users/eraykosterelioglu/Documents/machine_learning_notebook/machine_learning/notebook

In [31]:
import pandas as pd

data_path = "../job_salary_prediction_dataset.csv"
pd_data = pd.read_csv(data_path)

In [45]:
type(pd_data)

pandas.DataFrame

In [33]:
pd_data.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [36]:
pd_data.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [38]:
pd_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [41]:
pd_data.head().value_counts()

job_title           experience_years  education_level  skills_count  industry       company_size  location   remote_work  certifications  salary
AI Engineer         10                Bachelor         2             Healthcare     Medium        India      Hybrid       2               109413    1
Data Analyst        5                 Bachelor         17            Telecom        Small         Australia  No           0               93764     1
Frontend Developer  18                PhD              4             Media          Medium        Singapore  No           1               148123    1
Business Analyst    19                PhD              13            Retail         Medium        Canada     Yes          0               189123    1
Product Manager     15                Bachelor         7             Manufacturing  Large         Sweden     Yes          0               165069    1
Name: count, dtype: int64

In [35]:
pd_data.dtypes

job_title             str
experience_years    int64
education_level       str
skills_count        int64
industry              str
company_size          str
location              str
remote_work           str
certifications      int64
salary              int64
dtype: object

Normalizing Data

In [42]:
normalized_data = pd_data.value_counts(normalize=True)

In [44]:
normalized_data.head()

job_title           experience_years  education_level  skills_count  industry       company_size  location   remote_work  certifications  salary
AI Engineer         10                Bachelor         2             Healthcare     Medium        India      Hybrid       2               109413    0.000004
Data Analyst        5                 Bachelor         17            Telecom        Small         Australia  No           0               93764     0.000004
Frontend Developer  18                PhD              4             Media          Medium        Singapore  No           1               148123    0.000004
Business Analyst    19                PhD              13            Retail         Medium        Canada     Yes          0               189123    0.000004
Product Manager     15                Bachelor         7             Manufacturing  Large         Sweden     Yes          0               165069    0.000004
Name: proportion, dtype: float64

In [46]:
type(normalized_data)

pandas.Series

In [48]:
pd_data.certifications.value_counts()

certifications
0    42015
3    41974
2    41744
1    41574
4    41467
5    41226
Name: count, dtype: int64

In [49]:
type(pd_data.certifications)

pandas.Series

DataFrame consists of pandas series

In [50]:
pd_data.certifications.describe()

count    250000.000000
mean          2.491928
std           1.706475
min           0.000000
25%           1.000000
50%           2.000000
75%           4.000000
max           5.000000
Name: certifications, dtype: float64

In [58]:
cert = pd_data.certifications
cert

0         2
1         0
2         1
3         0
4         0
         ..
249995    1
249996    2
249997    0
249998    5
249999    5
Name: certifications, Length: 250000, dtype: int64

In [59]:
cert.describe()

count    250000.000000
mean          2.491928
std           1.706475
min           0.000000
25%           1.000000
50%           2.000000
75%           4.000000
max           5.000000
Name: certifications, dtype: float64

In [60]:
cert.head()

0    2
1    0
2    1
3    0
4    0
Name: certifications, dtype: int64

In [61]:
cert.argmax()

np.int64(7)

In [63]:
total = 0
for i in cert:
  total +=1
print(total)

250000

Typing Operations

In [64]:
numeric_values = pd_data.select_dtypes(include=["number"])

In [65]:
numeric_values.astype("float64")

        experience_years  skills_count  certifications    salary
0                   10.0           2.0             2.0  109413.0
1                    5.0          17.0             0.0   93764.0
2                   18.0           4.0             1.0  148123.0
3                   19.0          13.0             0.0  189123.0
4                   15.0           7.0             0.0  165069.0
...                  ...           ...             ...       ...
249995              17.0           2.0             1.0  127791.0
249996              20.0           7.0             2.0  154593.0
249997               1.0          12.0             0.0   75988.0
249998               0.0           2.0             5.0   90467.0
249999              16.0           2.0             5.0  133084.0

[250000 rows x 4 columns]

In [66]:
object_values = pd_data.select_dtypes(include=["object"])
object_values

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_45114/1285764039.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_values = pd_data.select_dtypes(include=["object"])

,job_title,education_level,industry,company_size,location,remote_work
0,AI Engineer,Bachelor,Healthcare,Medium,India,Hybrid
1,Data Analyst,Bachelor,Telecom,Small,Australia,No
2,Frontend Developer,PhD,Media,Medium,Singapore,No
3,Business Analyst,PhD,Retail,Medium,Canada,Yes
4,Product Manager,Bachelor,Manufacturing,Large,Sweden,Yes
...,...,...,...,...,...,...
249995,Software Engineer,PhD,Telecom,Enterprise,India,No
249996,Frontend Developer,PhD,Telecom,Startup,Remote,No
249997,Business Analyst,Bachelor,Retail,Enterprise,India,Yes
249998,Data Scientist,High School,Consulting,Small,Sweden,Hybrid
249999,Data Analyst,Diploma,Technology,Medium,UK,No

DataFrame Operations

In [67]:
import pandas as pd

In [74]:
diction = {
  "Students" : ["Eray","Rumeysa","Ahmet","Emirhan","Dogukan"],
  "Age" : [20,19,21,20,19],
  "Teachers" : ["Ozan","Elif","Ali","Ahmet","Murat"]
}

In [75]:
df_dict = pd.DataFrame(diction)

In [76]:
df_dict

  Students  Age Teachers
0     Eray   20     Ozan
1  Rumeysa   19     Elif
2    Ahmet   21      Ali
3  Emirhan   20    Ahmet
4  Dogukan   19    Murat

In [77]:
df_dict.head()

  Students  Age Teachers
0     Eray   20     Ozan
1  Rumeysa   19     Elif
2    Ahmet   21      Ali
3  Emirhan   20    Ahmet
4  Dogukan   19    Murat

In [78]:
df_dict.describe()

            Age
count   5.00000
mean   19.80000
std     0.83666
min    19.00000
25%    19.00000
50%    20.00000
75%    20.00000
max    21.00000

In [79]:
df_dict.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Students  5 non-null      str
 1   Age       5 non-null      int64
 2   Teachers  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [81]:
df_dict.index

RangeIndex(start=0, stop=5, step=1)

In [82]:
df_dict.tail()

  Students  Age Teachers
0     Eray   20     Ozan
1  Rumeysa   19     Elif
2    Ahmet   21      Ali
3  Emirhan   20    Ahmet
4  Dogukan   19    Murat

In [84]:
df_dict.head(3)

  Students  Age Teachers
0     Eray   20     Ozan
1  Rumeysa   19     Elif
2    Ahmet   21      Ali

In [85]:
df_dict["Age"]

0    20
1    19
2    21
3    20
4    19
Name: Age, dtype: int64

In [86]:
df_dict["Students"]

0       Eray
1    Rumeysa
2      Ahmet
3    Emirhan
4    Dogukan
Name: Students, dtype: str

In [87]:
df_dict["Students"].value_counts()

Students
Eray       1
Rumeysa    1
Ahmet      1
Emirhan    1
Dogukan    1
Name: count, dtype: int64

In [88]:
type(df_dict)

pandas.DataFrame

In [89]:
type(df_dict["Teachers"])

pandas.Series

In [90]:
df_dict_2 = pd.DataFrame(diction,index=["first","second","third","fourth","fifth"])
df_dict_2

       Students  Age Teachers
first      Eray   20     Ozan
second  Rumeysa   19     Elif
third     Ahmet   21      Ali
fourth  Emirhan   20    Ahmet
fifth   Dogukan   19    Murat

In [91]:
df_dict_2["Age"]

first     20
second    19
third     21
fourth    20
fifth     19
Name: Age, dtype: int64

In [93]:
two_col = ["Age","Students"]
df_dict_2[two_col]

        Age Students
first    20     Eray
second   19  Rumeysa
third    21    Ahmet
fourth   20  Emirhan
fifth    19  Dogukan

In [94]:
mask = df_dict_2[two_col]
mask

        Age Students
first    20     Eray
second   19  Rumeysa
third    21    Ahmet
fourth   20  Emirhan
fifth    19  Dogukan

In [96]:
df_dict_2.loc[["first","second","third"]]

       Students  Age Teachers
first      Eray   20     Ozan
second  Rumeysa   19     Elif
third     Ahmet   21      Ali

In [97]:
df_dict_2.loc[["first"]]

      Students  Age Teachers
first     Eray   20     Ozan

In [98]:
df_dict_2["adult"] = df_dict_2.Age >=18

In [99]:
df_dict_2

       Students  Age Teachers  adult
first      Eray   20     Ozan   True
second  Rumeysa   19     Elif   True
third     Ahmet   21      Ali   True
fourth  Emirhan   20    Ahmet   True
fifth   Dogukan   19    Murat   True

İloc and Loc Operations

In [101]:
df_dict_2

       Students  Age Teachers  adult
first      Eray   20     Ozan   True
second  Rumeysa   19     Elif   True
third     Ahmet   21      Ali   True
fourth  Emirhan   20    Ahmet   True
fifth   Dogukan   19    Murat   True

In [100]:
df_dict_2.iloc[1]

Students    Rumeysa
Age              19
Teachers       Elif
adult          True
Name: second, dtype: object

In [104]:
df_dict_2.iloc[1,[0,1]]

Students    Rumeysa
Age              19
Name: second, dtype: object

In [105]:
df_dict_2.iloc[1,[0,1,2]]

Students    Rumeysa
Age              19
Teachers       Elif
Name: second, dtype: object

In [106]:
df_dict_2.iloc[1:3]

       Students  Age Teachers  adult
second  Rumeysa   19     Elif   True
third     Ahmet   21      Ali   True

In [109]:
df_dict_2.iloc[[1,3]]

       Students  Age Teachers  adult
second  Rumeysa   19     Elif   True
fourth  Emirhan   20    Ahmet   True

In [110]:
df_dict_2.iloc[[1,3],[2]]

       Teachers
second     Elif
fourth    Ahmet

In [112]:
df_dict_2.iloc[[0,1,3],[2]]

       Teachers
first      Ozan
second     Elif
fourth    Ahmet

In [113]:
df_dict_2.iloc[[0,1,2],[0,1]]

       Students  Age
first      Eray   20
second  Rumeysa   19
third     Ahmet   21

In [128]:
import pandas as pd

data_path = "../job_salary_prediction_dataset.csv"
df = pd.read_csv(data_path)

In [115]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [116]:
df.drop(columns=['location'])

,job_title,experience_years,education_level,skills_count,industry,company_size,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Yes,0,165069
...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,No,5,133084

In [118]:
X = df.drop(columns="salary")

In [ ]:
y = df["salary"]

In [120]:
y

0         109413
1          93764
2         148123
3         189123
4         165069
           ...
249995    127791
249996    154593
249997     75988
249998     90467
249999    133084
Name: salary, Length: 250000, dtype: int64

In [121]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [129]:
df_num = df.select_dtypes(include="number")

In [130]:
df_num

        experience_years  skills_count  certifications  salary
0                     10             2               2  109413
1                      5            17               0   93764
2                     18             4               1  148123
3                     19            13               0  189123
4                     15             7               0  165069
...                  ...           ...             ...     ...
249995                17             2               1  127791
249996                20             7               2  154593
249997                 1            12               0   75988
249998                 0             2               5   90467
249999                16             2               5  133084

[250000 rows x 4 columns]

In [131]:
df_num.mul(3)

        experience_years  skills_count  certifications  salary
0                     30             6               6  328239
1                     15            51               0  281292
2                     54            12               3  444369
3                     57            39               0  567369
4                     45            21               0  495207
...                  ...           ...             ...     ...
249995                51             6               3  383373
249996                60            21               6  463779
249997                 3            36               0  227964
249998                 0             6              15  271401
249999                48             6              15  399252

[250000 rows x 4 columns]

In [132]:
import numpy as np

In [133]:
np_array = np.sqrt(df_num)

In [134]:
np_array

        experience_years  skills_count  certifications      salary
0               3.162278      1.414214        1.414214  330.776359
1               2.236068      4.123106        0.000000  306.209079
2               4.242641      2.000000        1.000000  384.867510
3               4.358899      3.605551        0.000000  434.882743
4               3.872983      2.645751        0.000000  406.286844
...                  ...           ...             ...         ...
249995          4.123106      1.414214        1.000000  357.478671
249996          4.472136      2.645751        1.414214  393.183163
249997          1.000000      3.464102        0.000000  275.659210
249998          0.000000      1.414214        2.236068  300.777326
249999          4.000000      1.414214        2.236068  364.806798

[250000 rows x 4 columns]

In [135]:
np.abs(np_array)

        experience_years  skills_count  certifications      salary
0               3.162278      1.414214        1.414214  330.776359
1               2.236068      4.123106        0.000000  306.209079
2               4.242641      2.000000        1.000000  384.867510
3               4.358899      3.605551        0.000000  434.882743
4               3.872983      2.645751        0.000000  406.286844
...                  ...           ...             ...         ...
249995          4.123106      1.414214        1.000000  357.478671
249996          4.472136      2.645751        1.414214  393.183163
249997          1.000000      3.464102        0.000000  275.659210
249998          0.000000      1.414214        2.236068  300.777326
249999          4.000000      1.414214        2.236068  364.806798

[250000 rows x 4 columns]

In [136]:
np.floor(np_array)

        experience_years  skills_count  certifications  salary
0                    3.0           1.0             1.0   330.0
1                    2.0           4.0             0.0   306.0
2                    4.0           2.0             1.0   384.0
3                    4.0           3.0             0.0   434.0
4                    3.0           2.0             0.0   406.0
...                  ...           ...             ...     ...
249995               4.0           1.0             1.0   357.0
249996               4.0           2.0             1.0   393.0
249997               1.0           3.0             0.0   275.0
249998               0.0           1.0             2.0   300.0
249999               4.0           1.0             2.0   364.0

[250000 rows x 4 columns]

In [137]:
df.sort_index()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [138]:
df.sort_index(axis = 1)

,certifications,company_size,education_level,experience_years,industry,job_title,location,remote_work,salary,skills_count
0,2,Medium,Bachelor,10,Healthcare,AI Engineer,India,Hybrid,109413,2
1,0,Small,Bachelor,5,Telecom,Data Analyst,Australia,No,93764,17
2,1,Medium,PhD,18,Media,Frontend Developer,Singapore,No,148123,4
3,0,Medium,PhD,19,Retail,Business Analyst,Canada,Yes,189123,13
4,0,Large,Bachelor,15,Manufacturing,Product Manager,Sweden,Yes,165069,7
...,...,...,...,...,...,...,...,...,...,...
249995,1,Enterprise,PhD,17,Telecom,Software Engineer,India,No,127791,2
249996,2,Startup,PhD,20,Telecom,Frontend Developer,Remote,No,154593,7
249997,0,Enterprise,Bachelor,1,Retail,Business Analyst,India,Yes,75988,12
249998,5,Small,High School,0,Consulting,Data Scientist,Sweden,Hybrid,90467,2
249999,5,Medium,Diploma,16,Technology,Data Analyst,UK,No,133084,2

In [140]:
df.sort_values(by="certifications")

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
143305,Backend Developer,9,Master,3,Healthcare,Startup,Singapore,No,0,112639
211028,Cybersecurity Analyst,4,High School,10,Finance,Medium,Sweden,Yes,0,107469
211027,Cybersecurity Analyst,13,Bachelor,13,Finance,Enterprise,Sweden,Yes,0,177169
211025,Business Analyst,3,Master,3,Technology,Startup,Germany,Hybrid,0,95151
211022,Data Scientist,12,PhD,13,Government,Enterprise,UK,Hybrid,0,219427
...,...,...,...,...,...,...,...,...,...,...
194939,Machine Learning Engineer,19,Bachelor,1,Government,Small,UK,Hybrid,5,180942
73425,Business Analyst,11,High School,2,Retail,Enterprise,Australia,Yes,5,122020
73423,Business Analyst,20,Diploma,4,Retail,Enterprise,Australia,No,5,150589
194952,Product Manager,18,Bachelor,4,Telecom,Startup,India,Yes,5,99209
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

Working with Iris Dataset

In [142]:
import pandas as pd

iris = pd.read_csv('../iris.csv')

In [143]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [144]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [145]:
iris.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [146]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [147]:
iris.sum()

Id                                                           11325
SepalLengthCm                                                876.5
SepalWidthCm                                                 458.1
PetalLengthCm                                                563.8
PetalWidthCm                                                 179.8
Species          Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

It returns the biggest value

In [149]:
iris.idxmax()

Id               149
SepalLengthCm    131
SepalWidthCm      15
PetalLengthCm    118
PetalWidthCm     100
Species          100
dtype: int64

It returns the smallest value

In [151]:
iris.idxmin()

Id                0
SepalLengthCm    13
SepalWidthCm     60
PetalLengthCm    22
PetalWidthCm      9
Species           0
dtype: int64

It returns cumulative sum

In [150]:
iris.cumsum()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,3,10.0,6.5,2.8,0.4,Iris-setosaIris-setosa
2,6,14.7,9.7,4.1,0.6,Iris-setosaIris-setosaIris-setosa
3,10,19.3,12.8,5.6,0.8,Iris-setosaIris-setosaIris-setosaIris-setosa
4,15,24.3,16.4,7.0,1.0,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
...,...,...,...,...,...,...
145,10731,851.6,446.2,543.1,171.8,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
146,10878,857.9,448.7,548.1,173.7,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
147,11026,864.4,451.7,553.3,175.7,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
148,11175,870.6,455.1,558.7,178.0,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
149,11325,876.5,458.1,563.8,179.8,Iris-setosaIris-setosaIris-setosaIris-setosaIr...

In [153]:
iris_num = iris.select_dtypes(include=["number"])

Correlation

In [ ]:
iris_num.corr()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Id,1.000000,0.716676,-0.397729,0.882747,0.899759
SepalLengthCm,0.716676,1.000000,-0.109369,0.871754,0.817954
SepalWidthCm,-0.397729,-0.109369,1.000000,-0.420516,-0.356544
PetalLengthCm,0.882747,0.871754,-0.420516,1.000000,0.962757
PetalWidthCm,0.899759,0.817954,-0.356544,0.962757,1.000000

You can give a target with corrwitha

In [ ]:
iris_num.corrwith("target")

Covaryans

In [156]:
iris_num.cov()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Id,1887.500000,25.782886,-7.492282,67.667785,29.832215
SepalLengthCm,25.782886,0.685694,-0.039268,1.273682,0.516904
SepalWidthCm,-7.492282,-0.039268,0.188004,-0.321713,-0.117981
PetalLengthCm,67.667785,1.273682,-0.321713,3.113179,1.296387
PetalWidthCm,29.832215,0.516904,-0.117981,1.296387,0.582414

In [158]:
df_dict_2

       Students  Age Teachers  adult
first      Eray   20     Ozan   True
second  Rumeysa   19     Elif   True
third     Ahmet   21      Ali   True
fourth  Emirhan   20    Ahmet   True
fifth   Dogukan   19    Murat   True

In [159]:
df_dict_2.value_counts()

Students  Age  Teachers  adult
Eray      20   Ozan      True     1
Rumeysa   19   Elif      True     1
Ahmet     21   Ali       True     1
Emirhan   20   Ahmet     True     1
Dogukan   19   Murat     True     1
Name: count, dtype: int64